### ISSUE TITLE
Effects of transitioning mel_base from '10' to 'e'

### ISSUE THREAD

**Issue by geckl** [openvpi/DiffSinger#195]
Hi All,

I'm attempting to inference a model I've trained and after weeks of debugging I've finally determined that my issues seem to be related to the mel_base setting. I understand that this repo recently transitioned from base 10 mel spectrograms to base e. These are the following things I've been thinking about, would love to hear everyone else's opinion on them:

1) Originally, my acoustic model utilized base 'e', while I'm assuming NSFHifiGan utilized base 10. Are there plans to release a base 'e' version of this vocoder?

2) As we move to base 'e', is there a problem with using old base 10 models for pretraining?

3) I tried manually "connecting" my base 'e' acoustic model with the base 10 vocoder by multiplying all the acoustic model output values by 0.434294 (the conversion rate between base e and base 10) but for some reason this didn't fully work? The vocals still sounded low quality and I'm not sure why. When I load my base 'e' acoustic model up in OpenUtau everything sounds fine, even though OU is using the same base 10 NSFHifiGan vocoder. Does anyone have any idea what they could possibly be doing to work with both base 'e' and base 10 models, besides simply multiplying by the 0.434294 conversion rate? (which doesn't seem to do the trick)

Any help is greatly appreciated!
Thanks

**Comment by yqzhishen** [comment]
1. Actually all vocoder models are under base e. The problem is that early acoustic models are all base 10. But this repo have conversion between the two bases so there is no problem.
2. Old base 10 models should not be used for pretraining under base e.
3. OpenUtau itself has a conversion process. It reads the configs and determine whether to multiply the scale factor. The compatibility between different bases has already been considered. If you write the configs honestly, everything should be okay.

**Comment by geckl** [comment]
Ah thank you that's very helpful. I saw the portion of OpenUtau code that converts between base 10 and base e, unfortunately though when I try to replicate this by inferencing my model in Javascript (using onnxruntime)  and multiplying by the sale factor I can't get the same results. I'll close this issue for now, and if I every figure out what my problem was I'll come back here and leave a comment. Thanks again!
